name: kcal_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  flutter_screenutil: 5.0.2
  flutter_svg: ^1.0.3
  dots_indicator: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Signika
      fonts:
        - asset: assets/fonts/Signika-Light.ttf
          weight: 300
        - asset: assets/fonts/Signika-Regular.ttf
          weight: 400
        - asset: assets/fonts/Signika-Medium.ttf
          weight: 500
        - asset: assets/fonts/Signika-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Signika-Bold.ttf
          weight: 700

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf